os: linux
sudo: required
dist: xenial

language: python

python:
  - 3.7
  - 3.6
  - 3.5
  - 3.4

install:
  - sudo apt-get update -q
  - sudo apt-get install --no-install-recommends -y xvfb gir1.2-gtk-3.0 python3-gi python3-gi-cairo libgirepository1.0-dev
  - pip install -r requirements.txt

script:
  - xvfb-run -a python3 -m unittest discover
