name: halo-weather
version: '0.2.1'
base: core18
summary: The Weather App
description: |
  An awesome weather app that will display your local weather.

grade: stable
confinement: strict
icon: halo/assets/halo.svg

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes

parts:
  desktop-gtk3:
    build-packages:
      - build-essential
      - libgtk-3-dev
    make-parameters:
      - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3
  pycairo:
    source: https://github.com/pygobject/pycairo/releases/download/v1.18.0/pycairo-1.18.0.tar.gz
    plugin: python
    python-version: python3
    build-packages:
      - libcairo2-dev
    stage-packages:
      - libcairo2
  pygobject:
    source: https://download.gnome.org/sources/pygobject/3.30/pygobject-3.30.4.tar.xz
    plugin: python
    python-version: python3
    after:
      - pycairo
    build-packages:
      - libglib2.0-dev
      - libgirepository1.0-dev
      - libffi-dev
    stage-packages:
      - libglib2.0-0
      - libgirepository-1.0-1
      - libffi6
      - libcairo-gobject2
  halo-weather:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - wheel
    build-packages:
      - python3-setuptools
      - pkg-config
    stage-packages:
      - python3-cairocffi
      - gir1.2-gtk-3.0
      - libcanberra-gtk3-0
      - libcanberra-gtk3-module
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - gnome-themes-standard
      - adwaita-icon-theme
      - shared-mime-info
      - fonts-lato
      - locales-all
    after:
      - pygobject
      - desktop-gtk3

apps:
  halo-weather:
    command: desktop-launch $SNAP/bin/halo-weather
    plugs:
      - home
      - network
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - gsettings
